management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        health: health
  endpoint:
    health:
      probes:
        enabled: true
      group:
        ready:
          include: "readinessState"
        live:
          include: "livenessState"